import { Global, Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

import {
  TagEntity,
  UserEntity,
  AlertEntity,
  ServerEntity,
  WalletEntity,
  ChannelEntity,
  CompanyEntity,
  LoyaltyEntity,
  AuditLogEntity,
  UserNoteEntity,
  WheelSpinEntity,
  UserAvatarEntity,
  UserDetailEntity,
  BillingInfoEntity,
  IntegrationEntity,
  UserSettingEntity,
  UserCompanyEntity,
  ExchangeRateEntity,
  OrganisationEntity,
  TradingEventEntity,
  UserDocumentEntity,
  CompanySettingEntity,
  LoyaltyHistoryEntity,
  PlatformClientEntity,
  TradingAccountEntity,
  UserAuthSessionEntity,
  UserNotificationEntity,
  TradingAccountTagEntity,
  WalletTransactionEntity,
  TradingAccountNoteEntity,
  PaymentTransactionEntity,
  TradingAccountTypeEntity,
  WalletTransactionHistoryEntity,
  TradingAccountTypeLeverageEntity,
} from '@crm/database';

import * as Validators from './validators';

const validators = [
  Validators.AlertIdValidator,
  Validators.AuditLogIdValidator,
  Validators.BillingInfoIdValidator,
  Validators.BooleanValidator,
  Validators.CompanyIdValidator,
  Validators.CompanySettingIdValidator,
  Validators.ExchangeRateIdValidator,
  Validators.IntegrationIdValidator,
  Validators.LoyaltyIdValidator,
  Validators.LoyaltyHistoryIdValidator,
  Validators.OrganisationIdValidator,
  Validators.PaymentTransactionIdValidator,
  Validators.PlatformClientIdValidator,
  Validators.PasswordValidator,
  Validators.ServerIdValidator,
  Validators.TagIdValidator,
  Validators.TradingAccountIdValidator,
  Validators.TradingAccountNoteIdValidator,
  Validators.TradingAccountTagIdValidator,
  Validators.TradingAccountTypeIdValidator,
  Validators.TradingAccountTypeLeverageIdValidator,
  Validators.TradingEventIdValidator,
  Validators.UserAuthSessionIdValidator,
  Validators.UserAvatarIdValidator,
  Validators.UserDetailIdValidator,
  Validators.UserDocumentIdValidator,
  Validators.UserIdValidator,
  Validators.UserNoteIdValidator,
  Validators.UserNotificationIdValidator,
  Validators.UserSettingIdValidator,
  Validators.WalletIdValidator,
  Validators.WalletTransactionIdValidator,
  Validators.WalletTransactionHistoryIdValidator,
  Validators.WheelSpinIdValidator,
];

@Global()
@Module({
  imports: [
    TypeOrmModule.forFeature([
      AlertEntity,
      AuditLogEntity,
      BillingInfoEntity,
      ChannelEntity,
      CompanyEntity,
      CompanySettingEntity,
      ExchangeRateEntity,
      IntegrationEntity,
      LoyaltyEntity,
      LoyaltyHistoryEntity,
      OrganisationEntity,
      PaymentTransactionEntity,
      PlatformClientEntity,
      ServerEntity,
      TagEntity,
      TradingAccountEntity,
      TradingAccountNoteEntity,
      TradingAccountTagEntity,
      TradingAccountTypeEntity,
      TradingAccountTypeLeverageEntity,
      TradingEventEntity,
      UserEntity,
      UserAuthSessionEntity,
      UserAvatarEntity,
      UserCompanyEntity,
      UserDetailEntity,
      UserDocumentEntity,
      UserNoteEntity,
      UserNotificationEntity,
      UserSettingEntity,
      WalletEntity,
      WalletTransactionEntity,
      WalletTransactionHistoryEntity,
      WheelSpinEntity,
    ]),
  ],
  providers: validators,
  exports: validators,
})
export class ValidationModule {}
