// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.1
// source: ReportingMessages.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

/** Domain event type */
export enum DomainEventType {
  /** DOMAIN_EVENT_TYPE_CREATE - Create */
  DOMAIN_EVENT_TYPE_CREATE = 0,
  /** DOMAIN_EVENT_TYPE_UPDATE - Update */
  DOMAIN_EVENT_TYPE_UPDATE = 1,
  /** DOMAIN_EVENT_TYPE_DELETE - Delete */
  DOMAIN_EVENT_TYPE_DELETE = 2,
  /** DOMAIN_EVENT_TYPE_UPDATE_DIFF - Update diff (incremental) */
  DOMAIN_EVENT_TYPE_UPDATE_DIFF = 3,
  UNRECOGNIZED = -1,
}

/** Access rights */
export enum AccessRights {
  /** ACCESS_RIGHTS_FULL_ACCESS - Full access */
  ACCESS_RIGHTS_FULL_ACCESS = 0,
  /** ACCESS_RIGHTS_CLOSE_ONLY - Close only */
  ACCESS_RIGHTS_CLOSE_ONLY = 1,
  /** ACCESS_RIGHTS_NO_TRADING - No trading */
  ACCESS_RIGHTS_NO_TRADING = 2,
  /** ACCESS_RIGHTS_NO_LOGIN - No login */
  ACCESS_RIGHTS_NO_LOGIN = 3,
  UNRECOGNIZED = -1,
}

/** Account type */
export enum AccountType {
  /** ACCOUNT_TYPE_HEDGED - Hedged */
  ACCOUNT_TYPE_HEDGED = 0,
  /** ACCOUNT_TYPE_NETTED - Netted */
  ACCOUNT_TYPE_NETTED = 1,
  /** ACCOUNT_TYPE_SPREAD_BETTING - Spread betting */
  ACCOUNT_TYPE_SPREAD_BETTING = 2,
  UNRECOGNIZED = -1,
}

export enum TotalMarginCalculationType {
  TYPE_MAX = 0,
  TYPE_SUM = 1,
  TYPE_NET = 2,
  UNRECOGNIZED = -1,
}

/** Asset type */
export enum AssetType {
  /** ASSET_TYPE_FOREX - Forex */
  ASSET_TYPE_FOREX = 0,
  /** ASSET_TYPE_METALS - Metals */
  ASSET_TYPE_METALS = 1,
  /** ASSET_TYPE_INDICES - Indices */
  ASSET_TYPE_INDICES = 2,
  /** ASSET_TYPE_COMMODITY - Commodity */
  ASSET_TYPE_COMMODITY = 3,
  /** ASSET_TYPE_STOCK - Stock */
  ASSET_TYPE_STOCK = 4,
  /** ASSET_TYPE_CRYPTO - Crypto */
  ASSET_TYPE_CRYPTO = 5,
  /** ASSET_TYPE_OTHER - Other */
  ASSET_TYPE_OTHER = 6,
  UNRECOGNIZED = -1,
}

/** Balance operation type */
export enum BalanceOperationType {
  /** BALANCE_OPERATION_TYPE_DEPOSIT - Deposit */
  BALANCE_OPERATION_TYPE_DEPOSIT = 0,
  /** BALANCE_OPERATION_TYPE_WITHDRAW - Withdraw */
  BALANCE_OPERATION_TYPE_WITHDRAW = 1,
  /** BALANCE_OPERATION_TYPE_CLOSE_POSITION - Close position */
  BALANCE_OPERATION_TYPE_CLOSE_POSITION = 2,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_STRATEGY_COMMISSION_INNER - Deposit strategy commission inner */
  BALANCE_OPERATION_TYPE_DEPOSIT_STRATEGY_COMMISSION_INNER = 3,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_STRATEGY_COMMISSION_INNER - Withdraw strategy commission inner */
  BALANCE_OPERATION_TYPE_WITHDRAW_STRATEGY_COMMISSION_INNER = 4,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_IB_COMMISSIONS - Deposit IB commissions */
  BALANCE_OPERATION_TYPE_DEPOSIT_IB_COMMISSIONS = 5,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_IB_SHARED_PERCENTAGE - Withdraw IB shared percentage */
  BALANCE_OPERATION_TYPE_WITHDRAW_IB_SHARED_PERCENTAGE = 6,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_SUB_IB - Deposit IB shared percentage from sub IB */
  BALANCE_OPERATION_TYPE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_SUB_IB = 7,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_BROKER - Deposit IB shared percentage from broker */
  BALANCE_OPERATION_TYPE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_BROKER = 8,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_REBATE - Deposit rebate */
  BALANCE_OPERATION_TYPE_DEPOSIT_REBATE = 9,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_REBATE - Withdraw rebate */
  BALANCE_OPERATION_TYPE_WITHDRAW_REBATE = 10,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_STRATEGY_COMMISSION_OUTER - Deposit strategy commission outer */
  BALANCE_OPERATION_TYPE_DEPOSIT_STRATEGY_COMMISSION_OUTER = 11,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_STRATEGY_COMMISSION_OUTER - Withdraw strategy commission outer */
  BALANCE_OPERATION_TYPE_WITHDRAW_STRATEGY_COMMISSION_OUTER = 12,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_BONUS_COMPENSATION - Withdraw bonus compensation */
  BALANCE_OPERATION_TYPE_WITHDRAW_BONUS_COMPENSATION = 13,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_IB_SHARED_PERCENTAGE_TO_BROKER - Withdraw IB shared percentage to broker */
  BALANCE_OPERATION_TYPE_WITHDRAW_IB_SHARED_PERCENTAGE_TO_BROKER = 14,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_DIVIDENDS - Deposit dividends */
  BALANCE_OPERATION_TYPE_DEPOSIT_DIVIDENDS = 15,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_DIVIDENDS - Withdraw dividends */
  BALANCE_OPERATION_TYPE_WITHDRAW_DIVIDENDS = 16,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_GSL_CHARGE - Withdraw GSL charge */
  BALANCE_OPERATION_TYPE_WITHDRAW_GSL_CHARGE = 17,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_ROLLOVER - Withdraw rollover */
  BALANCE_OPERATION_TYPE_WITHDRAW_ROLLOVER = 18,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_NONWITHDRAWABLE_BONUS - Deposit non-withdrawable bonus */
  BALANCE_OPERATION_TYPE_DEPOSIT_NONWITHDRAWABLE_BONUS = 19,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_NONWITHDRAWABLE_BONUS - Withdraw non-withdrawable bonus */
  BALANCE_OPERATION_TYPE_WITHDRAW_NONWITHDRAWABLE_BONUS = 20,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_SWAP - Swap deposit for limited risk account */
  BALANCE_OPERATION_TYPE_DEPOSIT_SWAP = 21,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_SWAP - Swap withdraw for limited risk account */
  BALANCE_OPERATION_TYPE_WITHDRAW_SWAP = 22,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_INVESTMENT_TO_STRATEGY - Withdrawal in case of trading to investment strategy */
  BALANCE_OPERATION_TYPE_WITHDRAW_INVESTMENT_TO_STRATEGY = 23,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_FROM_INVESTOR - Deposit to investment strategy's account in case of trading to this strategy */
  BALANCE_OPERATION_TYPE_DEPOSIT_FROM_INVESTOR = 24,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_RETURNED_INVESTMENT - Deposit in case of returning investments from strategy */
  BALANCE_OPERATION_TYPE_DEPOSIT_RETURNED_INVESTMENT = 25,
  /** BALANCE_OPERATION_TYPE_WITHDRAW_BY_INVESTOR - Withdrawal from investment strategy's account */
  BALANCE_OPERATION_TYPE_WITHDRAW_BY_INVESTOR = 26,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_MANAGEMENT_FEE - Deposit to the owner of an investment strategy from its account */
  BALANCE_OPERATION_TYPE_DEPOSIT_MANAGEMENT_FEE = 27,
  /**
   * BALANCE_OPERATION_TYPE_WITHDRAW_MANAGEMENT_FEE - Withdrawal from investment strategy's account to its owner
   *
   * @deprecated
   */
  BALANCE_OPERATION_TYPE_WITHDRAW_MANAGEMENT_FEE = 28,
  /** BALANCE_OPERATION_TYPE_DEPOSIT_PERFORMANCE_FEE - Deposit performance fee to the owner of an investment strategy */
  BALANCE_OPERATION_TYPE_DEPOSIT_PERFORMANCE_FEE = 29,
  /** BALANCE_WITHDRAW_FOR_SUBACCOUNT - Withdrawal from account to subaccount */
  BALANCE_WITHDRAW_FOR_SUBACCOUNT = 30,
  /** BALANCE_DEPOSIT_TO_SUBACCOUNT - Deposit to subaccount */
  BALANCE_DEPOSIT_TO_SUBACCOUNT = 31,
  /** BALANCE_WITHDRAW_FROM_SUBACCOUNT - Withdraw from subaccount */
  BALANCE_WITHDRAW_FROM_SUBACCOUNT = 32,
  /** BALANCE_DEPOSIT_FROM_SUBACCOUNT - Deposit from subaccount */
  BALANCE_DEPOSIT_FROM_SUBACCOUNT = 33,
  /** BALANCE_WITHDRAW_COPY_FEE - Withdrawal fees to Strategy Provider */
  BALANCE_WITHDRAW_COPY_FEE = 34,
  /** BALANCE_WITHDRAW_INACTIVITY_FEE - Withdraw of inactivity fee from the balance */
  BALANCE_WITHDRAW_INACTIVITY_FEE = 35,
  /** BALANCE_DEPOSIT_TRANSFER - Deposit from internal transfer */
  BALANCE_DEPOSIT_TRANSFER = 36,
  /** BALANCE_WITHDRAW_TRANSFER - Withdrawal from internal transfer */
  BALANCE_WITHDRAW_TRANSFER = 37,
  /** BALANCE_DEPOSIT_CONVERTED_BONUS - Deposit converted Bonus */
  BALANCE_DEPOSIT_CONVERTED_BONUS = 38,
  /** BALANCE_DEPOSIT_NEGATIVE_BALANCE_PROTECTION - Negative Balance Protection */
  BALANCE_DEPOSIT_NEGATIVE_BALANCE_PROTECTION = 39,
  UNRECOGNIZED = -1,
}

/** Bonus conversion type */
export enum BonusConversionType {
  /** BONUS_CONVERSION_TYPE_USD - USD */
  BONUS_CONVERSION_TYPE_USD = 0,
  /** BONUS_CONVERSION_TYPE_LOTS - Lots */
  BONUS_CONVERSION_TYPE_LOTS = 1,
  UNRECOGNIZED = -1,
}

/** Bonus operation type */
export enum BonusOperationType {
  /** BONUS_OPERATION_TYPE_DEPOSIT - Deposit */
  BONUS_OPERATION_TYPE_DEPOSIT = 0,
  /** BONUS_OPERATION_TYPE_WITHDRAW - Withdraw */
  BONUS_OPERATION_TYPE_WITHDRAW = 1,
  UNRECOGNIZED = -1,
}

/** Book type */
export enum BookType {
  /** BOOK_TYPE_BOOK_A - Book A */
  BOOK_TYPE_BOOK_A = 0,
  /** BOOK_TYPE_BOOK_B - Book B */
  BOOK_TYPE_BOOK_B = 1,
  UNRECOGNIZED = -1,
}

/** Commission type */
export enum CommissionType {
  /** USD_PER_MILLION_USD - USD per million USD volume - usually used for FX. Example: 50 USD for 1 mil USD of trading volume. In cents. */
  USD_PER_MILLION_USD = 0,
  /** USD_PER_LOT - USD per 1 lot - usually used for CFDs and futures for commodities, and indices. Example: 15 USD for 1 contract. In cents. */
  USD_PER_LOT = 1,
  /** PERCENTAGE_OF_VALUE - Percentage of trading volume - usually used for Equities. Example: 0.005% of notional trading volume. Multiplied by 100,000. */
  PERCENTAGE_OF_VALUE = 2,
  /** QUOTE_CCY_PER_LOT - Quote ccy of Symbol per 1 lot - will be used for CFDs and futures for commodities, and indices. Example: 15 EUR for 1 contract of DAX. In cents. */
  QUOTE_CCY_PER_LOT = 3,
  UNRECOGNIZED = -1,
}

/** Day of week */
export enum DayOfWeek {
  /** DAY_OF_WEEK_NONE - None */
  DAY_OF_WEEK_NONE = 0,
  /** DAY_OF_WEEK_MONDAY - Monday */
  DAY_OF_WEEK_MONDAY = 1,
  /** DAY_OF_WEEK_TUESDAY - Tuesday */
  DAY_OF_WEEK_TUESDAY = 2,
  /** DAY_OF_WEEK_WEDNESDAY - Wednesday */
  DAY_OF_WEEK_WEDNESDAY = 3,
  /** DAY_OF_WEEK_THURSDAY - Thursday */
  DAY_OF_WEEK_THURSDAY = 4,
  /** DAY_OF_WEEK_FRIDAY - Friday */
  DAY_OF_WEEK_FRIDAY = 5,
  /** DAY_OF_WEEK_SATURDAY - Saturday */
  DAY_OF_WEEK_SATURDAY = 6,
  /** DAY_OF_WEEK_SUNDAY - Sunday */
  DAY_OF_WEEK_SUNDAY = 7,
  UNRECOGNIZED = -1,
}

/** Deal status */
export enum DealStatus {
  /** DEAL_STATUS_FILLED - Filled */
  DEAL_STATUS_FILLED = 0,
  /** DEAL_STATUS_PARTIALLY_FILLED - Partially filled */
  DEAL_STATUS_PARTIALLY_FILLED = 1,
  /** DEAL_STATUS_REJECTED - Rejected */
  DEAL_STATUS_REJECTED = 2,
  /** DEAL_STATUS_INTERNALLY_REJECTED - Internally rejected */
  DEAL_STATUS_INTERNALLY_REJECTED = 3,
  /** DEAL_STATUS_ERROR - Error */
  DEAL_STATUS_ERROR = 4,
  /** DEAL_STATUS_MISSED - Missed */
  DEAL_STATUS_MISSED = 5,
  UNRECOGNIZED = -1,
}

/** Deal type */
export enum DealType {
  /** DEAL_TYPE_MARKET - Market */
  DEAL_TYPE_MARKET = 0,
  /** DEAL_TYPE_LIMIT - Limit */
  DEAL_TYPE_LIMIT = 1,
  UNRECOGNIZED = -1,
}

/** Market data entry type */
export enum MarketDataEntryType {
  /** MARKET_DATA_ENTRY_TYPE_BID - Bid */
  MARKET_DATA_ENTRY_TYPE_BID = 0,
  /** MARKET_DATA_ENTRY_TYPE_ASK - Ask */
  MARKET_DATA_ENTRY_TYPE_ASK = 1,
  UNRECOGNIZED = -1,
}

/** Min commission type */
export enum MinCommissionType {
  /** MIN_COMMISSION_TYPE_CURRENCY - Currency */
  MIN_COMMISSION_TYPE_CURRENCY = 0,
  /** MIN_COMMISSION_TYPE_QUOTE_CURRENCY - Quote currency */
  MIN_COMMISSION_TYPE_QUOTE_CURRENCY = 1,
  UNRECOGNIZED = -1,
}

/** Order status */
export enum OrderStatus {
  /** ORDER_STATUS_CREATED - Created */
  ORDER_STATUS_CREATED = 0,
  /** ORDER_STATUS_ACCEPTED - Accepted */
  ORDER_STATUS_ACCEPTED = 1,
  /** ORDER_STATUS_FILLED - Filled */
  ORDER_STATUS_FILLED = 2,
  /** ORDER_STATUS_REJECTED - Rejected */
  ORDER_STATUS_REJECTED = 3,
  /** ORDER_STATUS_EXPIRED - Expired */
  ORDER_STATUS_EXPIRED = 4,
  /** ORDER_STATUS_CANCELLED - Cancelled */
  ORDER_STATUS_CANCELLED = 5,
  /** ORDER_STATUS_RESERVED - Reserved */
  ORDER_STATUS_RESERVED = 6,
  UNRECOGNIZED = -1,
}

/** Order type */
export enum OrderType {
  /** ORDER_TYPE_MARKET - Market */
  ORDER_TYPE_MARKET = 0,
  /** ORDER_TYPE_LIMIT - Limit */
  ORDER_TYPE_LIMIT = 1,
  /** ORDER_TYPE_STOP - Stop */
  ORDER_TYPE_STOP = 2,
  /** ORDER_TYPE_STOP_LOSS_TAKE_PROFIT - Stop loss take profit */
  ORDER_TYPE_STOP_LOSS_TAKE_PROFIT = 3,
  /** ORDER_TYPE_MARKET_RANGE - Market range */
  ORDER_TYPE_MARKET_RANGE = 4,
  /** ORDER_TYPE_STOP_LIMIT - Stop Limit */
  ORDER_TYPE_STOP_LIMIT = 5,
  UNRECOGNIZED = -1,
}

/** Order trigger method */
export enum OrderTriggerMethod {
  /** ORDER_TRIGGER_METHOD_TRADE - Trade */
  ORDER_TRIGGER_METHOD_TRADE = 1,
  /** ORDER_TRIGGER_METHOD_OPPOSITE - Opposite */
  ORDER_TRIGGER_METHOD_OPPOSITE = 2,
  /** ORDER_TRIGGER_METHOD_DOUBLE_TRADE - Double Trade */
  ORDER_TRIGGER_METHOD_DOUBLE_TRADE = 3,
  /** ORDER_TRIGGER_METHOD_DOUBLE_OPPOSITE - Double Opposite */
  ORDER_TRIGGER_METHOD_DOUBLE_OPPOSITE = 4,
  UNRECOGNIZED = -1,
}

/** Position effect */
export enum PositionEffect {
  /** POSITION_EFFECT_NEW - New */
  POSITION_EFFECT_NEW = 0,
  /** POSITION_EFFECT_ALTER - Alter */
  POSITION_EFFECT_ALTER = 1,
  UNRECOGNIZED = -1,
}

/** Position status */
export enum PositionStatus {
  /** POSITION_STATUS_OPEN - Open */
  POSITION_STATUS_OPEN = 0,
  /** POSITION_STATUS_CLOSED - Closed */
  POSITION_STATUS_CLOSED = 1,
  /** POSITION_STATUS_CREATED - Created */
  POSITION_STATUS_CREATED = 2,
  /** POSITION_STATUS_ERROR - Error */
  POSITION_STATUS_ERROR = 3,
  UNRECOGNIZED = -1,
}

/** Symbol book type */
export enum SymbolBookType {
  /** SYMBOL_BOOK_TYPE_BOOK_A - Book A */
  SYMBOL_BOOK_TYPE_BOOK_A = 1,
  /** SYMBOL_BOOK_TYPE_BOOK_B - Book B */
  SYMBOL_BOOK_TYPE_BOOK_B = 2,
  UNRECOGNIZED = -1,
}

/** Time in force */
export enum TimeInForce {
  /** TIME_IN_FORCE_GOOD_TILL_DATE - Good till date */
  TIME_IN_FORCE_GOOD_TILL_DATE = 0,
  /** TIME_IN_FORCE_GOOD_TILL_CANCEL - Good till cancel */
  TIME_IN_FORCE_GOOD_TILL_CANCEL = 1,
  /** TIME_IN_FORCE_IMMEDIATE_OR_CANCEL - Immediate or cancel */
  TIME_IN_FORCE_IMMEDIATE_OR_CANCEL = 2,
  /** TIME_IN_FORCE_FILL_OR_KILL - Fill or kill */
  TIME_IN_FORCE_FILL_OR_KILL = 3,
  /** TIME_IN_FORCE_MARKET_ON_OPEN - Market on open */
  TIME_IN_FORCE_MARKET_ON_OPEN = 4,
  UNRECOGNIZED = -1,
}

/** Trade side */
export enum TradeSide {
  /** TRADE_SIDE_BUY - Buy */
  TRADE_SIDE_BUY = 0,
  /** TRADE_SIDE_SELL - Sell */
  TRADE_SIDE_SELL = 1,
  UNRECOGNIZED = -1,
}

/** Trading mode */
export enum TradingMode {
  TRADING_MODE_ENABLED = 0,
  TRADING_MODE_DISABLED_WITHOUT_PENDINGS_EXECUTION = 1,
  TRADING_MODE_DISABLED_WITH_PENDINGS_EXECUTION = 2,
  TRADING_MODE_CLOSE_ONLY_MODE = 3,
  UNRECOGNIZED = -1,
}

/** Type of OrderAction */
export enum ActionType {
  ACTION_TYPE_CREATE_STOP_LOSS_TAKE_PROFIT = 0,
  ACTION_TYPE_AMEND_STOP_LOSS_TAKE_PROFIT = 1,
  ACTION_TYPE_CANCEL_STOP_LOSS_TAKE_PROFIT = 2,
  ACTION_TYPE_CREATE_CLOSING_ORDER = 3,
  ACTION_TYPE_CREATE_ORDER = 4,
  ACTION_TYPE_CANCEL_PENDING_ORDER = 5,
  ACTION_TYPE_AMEND_OPEN_PENDING_ORDER = 6,
  ACTION_TYPE_CREATE_OCO_LINK = 7,
  ACTION_TYPE_CANCEL_OCO_LINK = 8,
  UNRECOGNIZED = -1,
}

/** Status of OrderAction */
export enum ActionStatus {
  ACTION_STATUS_PENDING = 0,
  ACTION_STATUS_STARTED = 1,
  ACTION_STATUS_PASSED = 2,
  ACTION_STATUS_FAILED = 3,
  ACTION_STATUS_ERROR = 4,
  UNRECOGNIZED = -1,
}

/** Specifies type of SWAP computation as PIPS (0) or PERCENTAGE (1, annual, in percent) */
export enum SwapCalculationType {
  PIPS = 0,
  PERCENTAGE = 1,
  /** POINTS - Specifies type of SWAP computation as POINTS (2) */
  POINTS = 2,
  UNRECOGNIZED = -1,
}

export enum GSLExecutionPolicy {
  DISABLED = 0,
  ENABLED_DECLINE_IF_A_BOOK = 1,
  ENABLED_FORCE_B_BOOK = 2,
  ENABLED_EXECUTE_INTO_SYMBOL_BOOK = 3,
  UNRECOGNIZED = -1,
}

/** Limited risk types */
export enum LimitedRiskMarginCalculationStrategy {
  ACCORDING_TO_LEVERAGE = 0,
  ACCORDING_TO_GSL = 1,
  ACCORDING_TO_GSL_AND_LEVERAGE = 2,
  UNRECOGNIZED = -1,
}

export enum SymbolDistanceType {
  SYMBOL_DISTANCE_IN_POINTS = 1,
  SYMBOL_DISTANCE_IN_PERCENTAGE = 2,
  UNRECOGNIZED = -1,
}

export enum ExecutionPolicy {
  BOOK_A = 1,
  BOOK_B = 2,
  BOOK_A_WITH_CONDITION = 3,
  UNRECOGNIZED = -1,
}

/** Assets */
export interface Assets {
  /** Asset */
  asset: Asset[];
}

/** Asset classes */
export interface AssetClasses {
  /** Asset class */
  assetClass: AssetClass[];
}

/** Authentications */
export interface Authentications {
  /** Authentication */
  authentication: Authentication[];
}

/** Balance histories */
export interface BalanceHistories {
  /** Balance history */
  balanceHistory: BalanceHistory[];
}

/** Bonus histories */
export interface BonusHistories {
  /** Bonus history */
  bonusHistory: BonusHistory[];
}

/** Countries */
export interface Countries {
  /** Country */
  country: Country[];
}

/** Deals */
export interface Deals {
  /** Deal */
  deal: Deal[];
}

/** Deal offsets */
export interface DealOffsets {
  /** Deal offsets */
  dealOffset: DealOffset[];
}

/** Dynamic Leverages */
export interface DynamicLeverageProfiles {
  /** Dynamic Leverages */
  dynamicLeverage: DynamicLeverageProfile[];
}

/** Orders */
export interface Orders {
  /** Order */
  order: Order[];
}

/** Positions */
export interface Positions {
  /** Position */
  position: Position[];
}

/** Price snapshots */
export interface PriceSnapshots {
  /** Prices snapshot */
  priceSnapshot: PriceSnapshot[];
}

/** Price streams */
export interface PriceStreams {
  /** Price stream */
  priceStream: PriceStream[];
}

/** Symbols */
export interface Symbols {
  /** Symbol */
  symbol: Symbol[];
}

/** Symbol categories */
export interface SymbolCategories {
  /** Symbol category */
  symbolCategory: SymbolCategory[];
}

/** Traders */
export interface Traders {
  /** Trader */
  trader: Trader[];
}

/** Trader groups */
export interface TraderGroups {
  /** Trader group */
  traderGroup: TraderGroup[];
}

/** Order actions */
export interface OrderActions {
  /** Order action */
  orderAction: OrderAction[];
}

/** Commission profiles */
export interface CommissionProfiles {
  /** Commission profile */
  commissionProfile: CommissionProfile[];
}

/** Volume profiles */
export interface VolumeProfiles {
  /** Volume profile */
  volumeProfile: VolumeProfile[];
}

/** Execution profiles */
export interface ExecutionProfiles {
  /** Execution profile */
  executionProfile: ExecutionProfile[];
}

/** Protection profiles */
export interface ProtectionProfiles {
  /** Protection profile */
  protectionProfile: ProtectionProfile[];
}

/** SwapFree profiles */
export interface SwapFreeProfiles {
  /** SwapFree profile */
  swapFreeProfile: SwapFreeProfile[];
}

/** Schedule profiles */
export interface ScheduleProfiles {
  /** Schedule profile */
  scheduleProfile: ScheduleProfile[];
}

/** SwapAndDividendProfile profiles */
export interface SwapAndDividendProfiles {
  /** SwapAndDividendProfile profile */
  swapAndDividendProfile: SwapAndDividendProfile[];
}

/** Holiday */
export interface Holidays {
  /** Holiday */
  holiday: Holiday[];
}

/** HolidayProfile profiles */
export interface HolidayProfiles {
  /** HolidayProfile profile */
  holidayProfile: HolidayProfile[];
}

/** Asset event */
export interface AssetEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Asset */
  asset: Asset | undefined;
}

/** Asset class event */
export interface AssetClassEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Asset class */
  assetClass: AssetClass | undefined;
}

/** Authentication event */
export interface AuthenticationEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Authentication */
  authentication: Authentication | undefined;
}

/** Balance history event */
export interface BalanceHistoryEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Balance history */
  balanceHistory: BalanceHistory | undefined;
}

/** Bonus history event */
export interface BonusHistoryEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Bonus history */
  bonusHistory: BonusHistory | undefined;
}

/** Deal event */
export interface DealEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Deal */
  deal: Deal | undefined;
}

/** DealOffsetsEvent - Event that returns DealOffsets for closing or reversing deals. Sent after a corresponding DealEvent */
export interface DealOffsetsEvent {
  /** Domain event type */
  type: DomainEventType;
  /** DealOffsets related to part of opening deals, that were offset by the executed closing deal */
  offsetting: DealOffset[];
}

/** DynamicLeverageEvent - Event that returns DynamicLeverage. Sent after a corresponding DynamicLeverageEvent */
export interface DynamicLeverageProfileEvent {
  /** Domain event type */
  type: DomainEventType;
  /** DynamicLeverage which affected by CRUD */
  dynamicLeverage: DynamicLeverageProfile | undefined;
}

/** Order event */
export interface OrderEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Order */
  order: Order | undefined;
}

/** Position event */
export interface PositionEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Position */
  position: Position | undefined;
}

/** Price snapshot event */
export interface PriceSnapshotEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Price snapshot */
  priceSnapshot: PriceSnapshot | undefined;
}

/** Swap calculation event */
export interface SwapCalculationEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Swap calculation */
  swapCalculation: SwapCalculation | undefined;
}

/** Price stream event */
export interface PriceStreamEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Price stream */
  priceStream: PriceStream | undefined;
}

/** Symbol event */
export interface SymbolEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Symbol */
  symbol: Symbol | undefined;
}

/** Symbol category event */
export interface SymbolCategoryEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Symbol category */
  symbolCategory: SymbolCategory | undefined;
}

/** Trader event */
export interface TraderEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Trader */
  trader: Trader | undefined;
}

/** Trader group event */
export interface TraderGroupEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Trader group */
  traderGroup: TraderGroup | undefined;
}

export interface GSLScheduleProfileEvent {
  type: DomainEventType;
  gslSchedule: GSLScheduleProfile | undefined;
}

export interface OCOOrdersLinkageEvent {
  type: DomainEventType;
  orderId1: Long;
  orderId2: Long;
}

export interface MarginCallEvent {
  type?: DomainEventType | undefined;
  marginCall: MarginCall | undefined;
}

export interface CommissionProfileEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Commission profile entity */
  commissionProfile: CommissionProfile | undefined;
}

export interface VolumeProfileEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Volume profile entity */
  volumeProfile: VolumeProfile | undefined;
}

export interface ExecutionProfileEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Execution profile entity */
  executionProfile: ExecutionProfile | undefined;
}

export interface ProtectionProfileEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Protection profile entity */
  protectionProfile: ProtectionProfile | undefined;
}

export interface SwapFreeProfileEvent {
  /** Domain event type */
  type: DomainEventType;
  /** SwapFree profile entity */
  swapFreeProfile: SwapFreeProfile | undefined;
}

export interface ScheduleProfileEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Schedule profile entity */
  scheduleProfile: ScheduleProfile | undefined;
}

export interface SwapAndDividendProfileEvent {
  /** Domain event type */
  type: DomainEventType;
  /** SwapAndDividendProfile profile entity */
  swapAndDividendProfile: SwapAndDividendProfile | undefined;
}

export interface HolidayEvent {
  /** Domain event type */
  type: DomainEventType;
  /** Holiday entity */
  holiday: Holiday | undefined;
}

export interface HolidayProfileEvent {
  /** Domain event type */
  type: DomainEventType;
  /** HolidayProfile profile entity */
  holidayProfile: HolidayProfile | undefined;
}

/** Asset */
export interface Asset {
  /** ID of the asset */
  id: Long;
  /** Asset name */
  name?:
    | string
    | undefined;
  /** Asset is used as a deposit asset */
  deposit?:
    | boolean
    | undefined;
  /** Asset could be used as a deposit currency */
  depositable?:
    | boolean
    | undefined;
  /** Specifies Type of the Asset. */
  type?:
    | AssetType
    | undefined;
  /** Name of the asset to be used on UI */
  displayName?: string | undefined;
}

/** Asset class */
export interface AssetClass {
  /** ID of the Asset Class */
  id: Long;
  /** Asset Class name */
  name?:
    | string
    | undefined;
  /** Specifies what is the default trading unit for the symbols of the Asset Class (1=Lots; 0=Units) */
  defaultLots?: boolean | undefined;
}

/** Authentication */
export interface Authentication {
  /** ID of the Authentication */
  id: Long;
  /** Trader login */
  login?:
    | Long
    | undefined;
  /** IP address of the Trader at the moment of authorization */
  ipAddress?:
    | string
    | undefined;
  /** Error in case of invalid authorization */
  errorCode?:
    | number
    | undefined;
  /** Date and time of authorization attempt */
  createTimestamp?:
    | Long
    | undefined;
  /** Session ID */
  sessionId?: string | undefined;
}

/** Balance history */
export interface BalanceHistory {
  /** ID of the Balance History event */
  id: Long;
  /** ID of the trader */
  traderId?:
    | Long
    | undefined;
  /** Delta value of operation */
  delta?:
    | Long
    | undefined;
  /** Account's balance after current transaction event */
  balance?:
    | Long
    | undefined;
  /** Type of operation */
  operationType?:
    | BalanceOperationType
    | undefined;
  /** Custom description for the transaction */
  description?:
    | string
    | undefined;
  /** Date and time of the transaction */
  createTimestamp?:
    | Long
    | undefined;
  /** Custom description for the transaction, visible to the trader */
  externalNote?:
    | string
    | undefined;
  /** Account's equity for the moment of the current Balance History event */
  equity?:
    | Long
    | undefined;
  /** Account's non-withdrawable bonus of the current Balance History event */
  nonWithdrawableBonus?:
    | Long
    | undefined;
  /** Source of payment */
  source?:
    | string
    | undefined;
  /** External payment id */
  externalId?:
    | string
    | undefined;
  /** Shows if monetary values were multiplied by 10^8 (TRUE) or by 10^2 (FALSE). Affects delta, balance, equity, nonWithdrawableBonus. */
  isPreciseMoney?: boolean | undefined;
}

/** Bonus history */
export interface BonusHistory {
  /** ID of the Bonus History event */
  id: Long;
  /** ID of the Trader */
  traderId?:
    | Long
    | undefined;
  /** Bonus delta, given by the Broker */
  managerDelta?:
    | Long
    | undefined;
  /** Total Bonus, given by the Broker */
  managerBonus?:
    | Long
    | undefined;
  /** Bonus delta, given by the IB */
  ibDelta?:
    | Long
    | undefined;
  /** Total Bonus, given by the IB */
  ibBonus?:
    | Long
    | undefined;
  /** Login of the IB, who gave the Bonus */
  introducingBrokerId?:
    | Long
    | undefined;
  /** Type of the Bonus transaction */
  operationType?:
    | BonusOperationType
    | undefined;
  /** Custom description for the transaction */
  description?:
    | string
    | undefined;
  /** Custom description for the transaction, visible to the trader */
  externalNote?:
    | string
    | undefined;
  /** Date and time of the transaction */
  createTimestamp?:
    | Long
    | undefined;
  /** Shows if monetary values were multiplied by 10^8 (TRUE) or by 10^2 (FALSE). Affects managerDelta, managerBonus, ibDelta, ibBonus. */
  isPreciseMoney?: boolean | undefined;
}

/** Country */
export interface Country {
  /** ID of the Country */
  id: Long;
  /** Name of the Country */
  name?: string | undefined;
}

/** Deal */
export interface Deal {
  /** ID */
  id: Long;
  /** ID of corresponding trade order */
  orderId?:
    | Long
    | undefined;
  /** Requested volume */
  volume?:
    | Long
    | undefined;
  /** Limit price for Deals from Market-Range Orders */
  limitPrice?:
    | Long
    | undefined;
  /** Trade side of the Deal */
  tradeSide?:
    | TradeSide
    | undefined;
  /** Date and time of the Deal creation */
  createTimestamp?:
    | Long
    | undefined;
  /** Base asset to Deposit conversion rate */
  marginRate?:
    | Long
    | undefined;
  /** Type of the Book */
  bookType?:
    | BookType
    | undefined;
  /** Status of the Deal */
  status?:
    | DealStatus
    | undefined;
  /** Volume, filled under this Deal */
  filledVolume?:
    | Long
    | undefined;
  /** Execution price of the Deal, including all markups */
  executionPrice?:
    | Long
    | undefined;
  /** Execution price of the Deal, excluding all markups */
  lpExecutionPrice?:
    | Long
    | undefined;
  /** Date and time of the Deal execution */
  executionTimestamp?:
    | Long
    | undefined;
  /** Order ID in the LP's side */
  lpOrderId?:
    | string
    | undefined;
  /** Type of the Deal */
  type?:
    | DealType
    | undefined;
  /** Charged commission for the Deal */
  tradingCommission?:
    | Long
    | undefined;
  /** Date and time of the last update of the Deal */
  lastUpdateTimestamp?:
    | Long
    | undefined;
  /** ID of the related Price Snapshot (snapshot of the prices at the moment of creation of the Deal) */
  priceSnapshotId?:
    | Long
    | undefined;
  /** Base asset to USD conversion rate */
  baseToUsdConversionRate?:
    | number
    | undefined;
  /** Additional commission which will be paid to the IB for the Deal */
  ibCommission?:
    | Long
    | undefined;
  /** Commission which Broker will pay to IB for the Deal. Always in USD (cents) */
  pocketCommission?:
    | Long
    | undefined;
  /** Markup (in terms of the price) which Broker will pay to IB for the Deal. Always in USD (cents) */
  pocketMarkup?:
    | Long
    | undefined;
  /** ID of the IB who will get IB commissions for the Deal */
  parentIntroducingBrokerId?:
    | Long
    | undefined;
  /** Amount of commission which trader pays to Spotware for providing some strategy in cMirror */
  mirroringCommission?:
    | Long
    | undefined;
  /** Markup value (in USD) of the Deal */
  markup?:
    | Long
    | undefined;
  /** Lot size of the symbol at the moment of the Deal creation */
  lotSize?:
    | Long
    | undefined;
  /** Stake, filled under this Deal */
  stake?:
    | Long
    | undefined;
  /** Price desired by the client as an execution price */
  desiredVwap?:
    | Long
    | undefined;
  /** Real market VWAP at the moment of execution of the Deal */
  marketVwap?:
    | Long
    | undefined;
  /** Reason of the rejection of the Deal */
  rejectReason?:
    | string
    | undefined;
  /** Total USD volume of the Account from the beginning of time */
  totalVolumeInUSD?:
    | Long
    | undefined;
  /** related ClosePositionDetail */
  closePositionDetail?:
    | ClosePositionDetail
    | undefined;
  /** ID of the Trader */
  traderId?:
    | Long
    | undefined;
  /** Shows if monetary values were multiplied by 10^8 (TRUE) or by 10^2 (FALSE). Affects tradingCommission, ibCommission, mirroringCommission. */
  isPreciseMoney?: boolean | undefined;
  symbolId?: Long | undefined;
  positionId?: Long | undefined;
}

export interface ClosePositionDetail {
  /** ID of related deal */
  dealId: Long;
  /** Opening VWAP of the position at the moment of filling the closing order */
  entryPrice?:
    | Long
    | undefined;
  /** Price of the Stop Loss */
  stopLoss?:
    | Long
    | undefined;
  /** Price of the Take Profit */
  takeProfit?:
    | Long
    | undefined;
  /** ID of the related BalanceHistory */
  balanceHistoryId?:
    | Long
    | undefined;
  /**
   * Quote asset to deposit asset conversion rate
   *
   * @deprecated
   */
  quoteToDepositConversionRate?:
    | Long
    | undefined;
  /** Volume, closed by the  related Deal */
  closedVolume?:
    | Long
    | undefined;
  /** SWAP, realized by the  related Deal */
  realizedSwap?:
    | Long
    | undefined;
  /** Commission, realized by the related Deal */
  realizedTradingCommission?:
    | Long
    | undefined;
  /** IB commission, realized by the related Deal */
  realizedIbCommission?:
    | Long
    | undefined;
  /** Realized commission which Broker will pay to IB. Always in USD (cents) */
  realizedPocketCommission?:
    | Long
    | undefined;
  /** Realized markup (in money) which Broker will pay to IB. Always in USD (cents) */
  realizedPocketMarkup?:
    | Long
    | undefined;
  /** Realized commission which trader pays to Spotware for providing some strategy in cMirror */
  realizedMirroringCommission?:
    | Long
    | undefined;
  /** Deposit asset to IB Deposit asset conversion rate */
  depositToIbDepositConversionRate?:
    | Long
    | undefined;
  /** Rebate which will be returned to the trader */
  rebate?:
    | Long
    | undefined;
  /** Markup, realized by the related Deal. Always in USD (cents) */
  realizedMarkup?:
    | Long
    | undefined;
  /** Stake, realized by the related Deal */
  closedStake?:
    | Long
    | undefined;
  /** Specifies either IB received all commissions from the ClosePositionDetail or not */
  ibCommissionsPaid?:
    | boolean
    | undefined;
  /** Execution timestamp of the first offset opening Deal for the closing Deal */
  offsetDealTimestamp?:
    | Long
    | undefined;
  /**
   * Realized value of Performance Fee
   *
   * @deprecated
   */
  performanceFee?:
    | Long
    | undefined;
  /** Quote asset to deposit asset conversion rate as double value (e.g. 1.23456) */
  quoteToDeposit?:
    | number
    | undefined;
  /** Gross realized profit related to the closing of offset part of opening deals */
  profit?:
    | Long
    | undefined;
  /** Shows if monetary values were multiplied by 10^8 (TRUE) or by 10^2 (FALSE). Affects realizedSwap, realizedTradingCommission, realizedIbCommission, realizedMirroringCommission, rebate, profit */
  isPreciseMoney?:
    | boolean
    | undefined;
  /** Charge for PnL conversion. This is actual fee, applied to the Deal in account's ccy. */
  pnlConversionFee?: Long | undefined;
}

export interface DealOffset {
  /** ID */
  id: Long;
  openDealId: Long;
  closingDealId: Long;
  volume: Long;
  stake: Long;
  swap: Long;
}

export interface DynamicLeverageProfile {
  /** ID of related Dynamic Leverage */
  id: Long;
  /** Name of the Dynamic Leverage */
  name: string;
  /** Description of the Dynamic Leverage */
  description?:
    | string
    | undefined;
  /** Specifies either Group is deleted or not */
  deleted?:
    | boolean
    | undefined;
  /** Dynamic leverage tiers of the Dynamic Leverage */
  tiers: DynamicLeverageTier[];
}

export interface DynamicLeverageTier {
  /** Volume of tier */
  volume: Long;
  /** Leverage of tier */
  leverage: number;
}

/** Order */
export interface Order {
  /** ID of the Order */
  id: Long;
  /** ID of the related Position */
  positionId?:
    | Long
    | undefined;
  /** Type of the Order */
  type?:
    | OrderType
    | undefined;
  /** Volume, requested in the Order */
  volume?:
    | Long
    | undefined;
  /** Limit price of the Order. Used for Orders with orderType=1 and 3 */
  limitPrice?:
    | Long
    | undefined;
  /** Date and time of automatic cancellation of the pending Order */
  expirationTimestamp?:
    | Long
    | undefined;
  /** Date and time of the Order creation */
  createTimestamp?:
    | Long
    | undefined;
  /** Trade direction */
  tradeSide?:
    | TradeSide
    | undefined;
  /** Order status */
  status?:
    | OrderStatus
    | undefined;
  /** Date and time of closing of the Order */
  closeTimestamp?:
    | Long
    | undefined;
  /** Specifies either Order is reduces volume of the position or not */
  closing?:
    | boolean
    | undefined;
  /** Stop price of the Order. Used for Orders with orderType=2 and 3 */
  stopPrice?:
    | Long
    | undefined;
  /** Date and time of last Order modification */
  lastUpdateTimestamp?:
    | Long
    | undefined;
  /** Worst execution price, according to desired maximum slippage. Used for Orders with orderType=4 */
  slippagePrice?:
    | Long
    | undefined;
  /** Maximum slippage in pips for the Order. Used for Orders with orderType=4 */
  slippage?:
    | number
    | undefined;
  /** Custom Order label. Usually used by the cBots */
  label?:
    | string
    | undefined;
  /** Custom Order channel. Usually specifies way of Order creation */
  channel?:
    | string
    | undefined;
  /** Custom Order comment. Usually used by the humans */
  comment?:
    | string
    | undefined;
  /** Stop Loss price. Is a price of the Stop Loss which will be placed if the Order is filled. */
  stopLoss?:
    | Long
    | undefined;
  /** Take Profit price. Is a price of the Take Profit which will be placed if the Order is filled. */
  takeProfit?:
    | Long
    | undefined;
  /** Relative Stop Loss distance. Specifies distance between execution price of the order and placed Stop Loss. */
  relativeStopLoss?:
    | Long
    | undefined;
  /** Relative Take Profit distance. Specifies distance between execution price of the order and placed Take Profit. */
  relativeTakeProfit?:
    | Long
    | undefined;
  /** Internal Order ID */
  clientOrderId?:
    | string
    | undefined;
  /** Time In Force of the Order */
  timeInForce?:
    | TimeInForce
    | undefined;
  /** Book of the Order */
  bookType?:
    | BookType
    | undefined;
  /** Lot size of the related Symbol at the moment of Order creation */
  lotSize?:
    | Long
    | undefined;
  /** Stake requested in the Order */
  stake?:
    | Long
    | undefined;
  /** Price desired by the client as an execution price */
  desiredVwap?:
    | Long
    | undefined;
  /** Specifies either related Stop Loss is guaranteed or not */
  guaranteedStopLoss?:
    | boolean
    | undefined;
  /** Specifies either tolerance check should be applied at the moment of execution or not */
  checkTolerance?:
    | boolean
    | undefined;
  /** Specifies either Order is Stop Out or not */
  stopOut?:
    | boolean
    | undefined;
  /** Specifies either related Stop Loss is trailing or not */
  trailingStopLoss?:
    | boolean
    | undefined;
  /** Trigger method for main pending order */
  stopTriggerMethod?:
    | OrderTriggerMethod
    | undefined;
  /** Stop trigger method for SL/TP order */
  stopLossTriggerMethod?:
    | OrderTriggerMethod
    | undefined;
  /** Maximum slippage in pips for the Order. Used for Orders with orderType=4 */
  slippageInPoints?:
    | number
    | undefined;
  /** Date and time for execution MOO order */
  desiredOpenTimestamp?:
    | Long
    | undefined;
  /** Id of linked OCO order */
  ocoOrderId?:
    | Long
    | undefined;
  /** ID of the Trader */
  traderId?: Long | undefined;
}

/** Position */
export interface Position {
  /** ID of the Position */
  id: Long;
  /** ID of the traded Symbol */
  symbolId?:
    | Long
    | undefined;
  /** Date and time of closing Position */
  closeTimestamp?:
    | Long
    | undefined;
  /** ID of the Trader */
  traderId?:
    | Long
    | undefined;
  /** Status of the Position */
  status?:
    | PositionStatus
    | undefined;
  /** Applied Stop Loss */
  stopLoss?:
    | Long
    | undefined;
  /** Applied Take Profit */
  takeProfit?:
    | Long
    | undefined;
  /** Date and time of the last update of the Position */
  lastUpdateTimestamp?:
    | Long
    | undefined;
  /** Book of the Position */
  bookType?:
    | BookType
    | undefined;
  /** Date and time of the opening of the Position */
  openTimestamp?:
    | Long
    | undefined;
  /** Specifies either Position is spread-betting or not */
  spreadBetting?:
    | boolean
    | undefined;
  /** Specifies either related Stop Loss is guaranteed or not */
  guaranteedStopLoss?:
    | boolean
    | undefined;
  /** Specifies either related Stop Loss is trailing or not */
  trailingStopLoss?:
    | boolean
    | undefined;
  /** Used margin in cents */
  usedMargin?:
    | Long
    | undefined;
  /** Shows if monetary values were multiplied by 10^8 (TRUE) or by 10^2 (FALSE). Affects usedMargin */
  isPreciseMoney?: boolean | undefined;
}

/** Price snapshot */
export interface PriceSnapshot {
  /** ID of the Price Snapshot */
  id: Long;
  /** ID of the Symbol */
  symbolId?:
    | Long
    | undefined;
  /** Price details */
  priceSnapshotEntry: PriceSnapshot_Entry[];
}

/** Price snapshot entry */
export interface PriceSnapshot_Entry {
  /** Available price */
  price?:
    | Long
    | undefined;
  /** Price direction */
  type?:
    | MarketDataEntryType
    | undefined;
  /** Available volume at the specified price */
  volume?:
    | Long
    | undefined;
  /** Date and time of price appearing */
  createTimestamp?: Long | undefined;
}

/** Swap calculations */
export interface SwapCalculations {
  /** Swap calculation */
  swapCalculation: SwapCalculation[];
}

/** Swap calculation */
export interface SwapCalculation {
  /** ID of the SWAP calculation event */
  id: Long;
  /** ID ot the relevant Position */
  positionId: Long;
  /** Amount of SWAP charged for the specified Position */
  chargedSwap: Long;
  /** Full amount of SWAP for the specified Position */
  currentSwap: Long;
  /** Date and time of the calculation event */
  createTimestamp: Long;
  /** Shows if monetary values were multiplied by 10^8 (TRUE) or by 10^2 (FALSE). Affects chargedSwap, currentSwap */
  isPreciseMoney?: boolean | undefined;
}

/** Price stream */
export interface PriceStream {
  /** ID of the Price Stream */
  id: Long;
  /** Name of the Price Stream */
  name?:
    | string
    | undefined;
  /** Description for the Price Stream */
  description?:
    | string
    | undefined;
  /** Specifies either Price Stream removed or not */
  deleted?:
    | boolean
    | undefined;
  /** Date and time of the last update of the Price Stream */
  lastUpdateTimestamp?:
    | Long
    | undefined;
  /** Price Stream Symbol */
  priceStreamSymbol: PriceStream_Symbol[];
}

/** Price stream symbol */
export interface PriceStream_Symbol {
  /** ID of the Price Stream Symbol */
  symbolId?:
    | Long
    | undefined;
  /** Bid markup value */
  bidMarkup?:
    | number
    | undefined;
  /** Ask markup value */
  askMarkup?:
    | number
    | undefined;
  /** Specifies type of the markup (1 = relative; 0 = absolute) */
  relativeMarkup?: boolean | undefined;
}

/** Symbol */
export interface Symbol {
  /** ID of the Symbol */
  id: Long;
  /** Name of the Symbol */
  name?:
    | string
    | undefined;
  /** Description for the Symbol */
  description?:
    | string
    | undefined;
  /** Amount of digits after comma in the price */
  digits?:
    | number
    | undefined;
  /** Specifies digit which is used for determining pip position */
  pipPosition?:
    | number
    | undefined;
  /** Specifies ether Symbol is turned on for price streaming or not */
  lpEnabled?:
    | boolean
    | undefined;
  /** Specifies ether Symbol is visible in cTrader or not */
  enabled?:
    | boolean
    | undefined;
  /** Date and time of the last update of the Symbol */
  lastUpdateTimestamp?:
    | Long
    | undefined;
  /** Bid markup value */
  bidMarkup?:
    | number
    | undefined;
  /** Ask markup value */
  askMarkup?:
    | number
    | undefined;
  /** Specifies which unit is traded under base asset */
  measurementUnits?:
    | string
    | undefined;
  /** ID of the base asset */
  baseAssetId?:
    | Long
    | undefined;
  /** ID of the quote asset */
  quoteAssetId?:
    | Long
    | undefined;
  /** Timeout for last quote expiration */
  quoteExpirationTimeout?:
    | number
    | undefined;
  /**
   * Book of the Symbol
   *
   * @deprecated
   */
  symbolBookType?:
    | SymbolBookType
    | undefined;
  /** Amount of units of the base asset in one lot */
  lotSize?:
    | Long
    | undefined;
  /** Specifies either short selling is allowed or not */
  shortSellingEnabled?:
    | boolean
    | undefined;
  /** ID of the Symbol Category where Symbol is located */
  symbolCategoryId?:
    | Long
    | undefined;
  /** Specifies either Symbol is marked as popular or not */
  favorite?:
    | boolean
    | undefined;
  /**
   * Specifies either guaranteed Stop Loss  is allowed or not
   *
   * @deprecated
   */
  guaranteedStopLoss?:
    | boolean
    | undefined;
  /** Custom tags. Used for searching Symbols */
  tags?:
    | string
    | undefined;
  /** Specified trading mode for the symbol that limits scope of trading operations */
  tradingMode?:
    | TradingMode
    | undefined;
  /** Price alias specified for the current price liquidity feed of the Symbol */
  priceAlias?:
    | string
    | undefined;
  /** Trade alias specified for the current trade liquidity feed of the Symbol */
  tradeAlias?:
    | string
    | undefined;
  /**
   * Gsl execution policy
   *
   * @deprecated
   */
  defaultGSLExecutionPolicy?:
    | GSLExecutionPolicy
    | undefined;
  /** Default commission profile for symbol */
  defaultCommissionProfileId?:
    | Long
    | undefined;
  /** Default volume profile for symbol */
  defaultVolumeProfileId?:
    | Long
    | undefined;
  /** Default execution profile for symbol */
  defaultExecutionProfileId?:
    | Long
    | undefined;
  /** Default protection profile for symbol */
  defaultProtectionProfileId?:
    | Long
    | undefined;
  /** Default swapFree profile for symbol */
  defaultSwapFreeProfileId?:
    | Long
    | undefined;
  /** Default GSL schedule id for symbol */
  defaultGSLScheduleId?:
    | Long
    | undefined;
  /** Schedule profile for symbol */
  scheduleProfileId?:
    | Long
    | undefined;
  /** Symbol holiday profile id */
  holidayProfileId?:
    | Long
    | undefined;
  /** Swap is calculated every swapPeriod hours */
  defaultSwapPeriod?:
    | number
    | undefined;
  /** Time in minutes from 00:00 (UTC) from which swap period is calculated */
  defaultSwapTime?: number | undefined;
}

/** Symbol category */
export interface SymbolCategory {
  /** ID of the Symbol Category */
  id: Long;
  /** ID of the Asset Class which contains Symbol category */
  assetClassId?:
    | Long
    | undefined;
  /** Name of the Symbol Category */
  name?: string | undefined;
}

/** Trader */
export interface Trader {
  /** ID of the account */
  id: Long;
  /** ID of the Group where Trader is */
  traderGroupId?:
    | Long
    | undefined;
  /** Trader login */
  login?:
    | Long
    | undefined;
  /** Specifies either Trader is deleted or not */
  deleted?:
    | boolean
    | undefined;
  /** Trader's name */
  name?:
    | string
    | undefined;
  /** Trader's country ID */
  countryId?:
    | Long
    | undefined;
  /** Trader's city */
  city?:
    | string
    | undefined;
  /** Trader's state */
  state?:
    | string
    | undefined;
  /** Trader's ZIP */
  zipCode?:
    | string
    | undefined;
  /** Trader's address */
  address?:
    | string
    | undefined;
  /** Trader's phone number */
  phone?:
    | string
    | undefined;
  /** Trader's email */
  email?:
    | string
    | undefined;
  /** Description for the Trader */
  description?:
    | string
    | undefined;
  /** Trader's document ID */
  documentId?:
    | string
    | undefined;
  /** Trader's status */
  status?:
    | string
    | undefined;
  /** Date and time of the account's registration */
  registrationTimestamp?:
    | Long
    | undefined;
  /** Date and time of the Trader's last successful authorization */
  lastConnectionTimestamp?:
    | Long
    | undefined;
  /** CDate and time of the last update of the account */
  lastUpdateTimestamp?:
    | Long
    | undefined;
  /**
   * Custom field to determine IB one
   *
   * @deprecated
   */
  introducingBroker1?:
    | string
    | undefined;
  /**
   * Custom field to determine IB two
   *
   * @deprecated
   */
  introducingBroker2?:
    | string
    | undefined;
  /** Type of the account */
  accountType?:
    | AccountType
    | undefined;
  /** Deposit asset */
  depositAssetId?:
    | Long
    | undefined;
  /** Specifies either account is IB or not */
  introducingBroker?:
    | boolean
    | undefined;
  /** Specifies ID of the account who introduced current account */
  parentIntroducingBrokerId?:
    | Long
    | undefined;
  /** Additional commission which trader will pay to IB */
  ibCommissionRate?:
    | number
    | undefined;
  /** Commission which Broker will pay to IB for the Deal of the Trader */
  pocketCommissionRate?:
    | number
    | undefined;
  /** Markup which Broker will pay to IB for the Deal of the Trader */
  pocketMarkupRate?:
    | number
    | undefined;
  /** Last name of the Trader */
  lastName?:
    | string
    | undefined;
  /** Specifies either account Broker will split markup and commission revenue with IB or not */
  splitRevenue?:
    | boolean
    | undefined;
  /** Amount of bonus, given by the Broker */
  managerBonus?:
    | Long
    | undefined;
  /** Amount of bonus, given by the IB */
  ibBonus?:
    | Long
    | undefined;
  /**
   * Specifies either account is “limited risk” or not
   *
   * @deprecated
   */
  limitedRisk?:
    | boolean
    | undefined;
  /** Type of the access of the account */
  accessRights?:
    | AccessRights
    | undefined;
  /** Specifies either EOD statement should be send to the Trader or not */
  sendOwnStatement?:
    | boolean
    | undefined;
  /** Date and time of the last logout */
  logoutTimestamp?:
    | Long
    | undefined;
  /** Specifies either account is SWAP-free or not */
  swapFree?:
    | boolean
    | undefined;
  /** Amount of non-withdrawable bonus, given by the Broker */
  nonWithdrawableBonus?:
    | Long
    | undefined;
  /** Account's leverage in cents */
  leverageInCents?:
    | number
    | undefined;
  /** Total margin calculation type. Can be TYPE_MAX = 0, TYPE_SUM = 1 or TYPE_NET = 2 */
  totalMarginCalculationType?:
    | TotalMarginCalculationType
    | undefined;
  /**
   * Specifies either account is “french risk” or not
   *
   * @deprecated
   */
  frenchRisk?:
    | boolean
    | undefined;
  /** Determine parent account of account, if it is sub account. Used for copy service */
  subAccountOf?:
    | Long
    | undefined;
  /** Net Open Position limit or NOP. Value = 1 equals to 0.01% */
  maxNOP?:
    | number
    | undefined;
  /** Specifies either account is of limited risk type */
  isLimitedRisk?:
    | boolean
    | undefined;
  /** Limited risk type */
  limitedRiskMarginCalculationStrategy?:
    | LimitedRiskMarginCalculationStrategy
    | undefined;
  /**
   * management fees - are part of annual percentage (management fee, specified by the Provider), calculated nightly by the
   * Copy as part of the equity at the moment of nightly job
   */
  managementFee?:
    | Long
    | undefined;
  /** Send statement to broker */
  sendStatementToBroker?:
    | boolean
    | undefined;
  /** Determines how ibCommissionRate and pocketCommissionRate will be treated */
  ibCommissionsType?:
    | CommissionType
    | undefined;
  /** Balance of the account */
  balance?: Long | undefined;
}

/** Trader group */
export interface TraderGroup {
  /** ID of the Group */
  id: Long;
  /** Name of the Group */
  name?:
    | string
    | undefined;
  /** Group description */
  description?:
    | string
    | undefined;
  /** Specifies either Group is deleted or not */
  deleted?:
    | boolean
    | undefined;
  /** Specifies either Group is enabled (trader's login are allowed) or not */
  enabled?:
    | boolean
    | undefined;
  /** Specifies either SWAP charging is enabled or not */
  swapEnabled?:
    | boolean
    | undefined;
  /** Level of the Stop Out */
  stopOutLevel?:
    | number
    | undefined;
  /** Date and time of the last Group modification */
  lastUpdateTimestamp?:
    | Long
    | undefined;
  /** ID of the related Price Stream */
  priceStreamId?:
    | Long
    | undefined;
  /** Specifies bonus conversion strategy (1 – Lots into USD; 0 – USD volume into USD) */
  bonusConversionType?:
    | BonusConversionType
    | undefined;
  /** Amount of traded lots to convert one bonus USD into one deposit USD. Used if bonusConvertLots=1 */
  bonusUsdConversionRate?:
    | number
    | undefined;
  /** Amount of traded USD volume to convert one bonus USD into one deposit USD. Used if bonusConvertLots=0 */
  bonusLotsConversionRate?:
    | number
    | undefined;
  /** Specifies either Group is Dealing Desk or not */
  dealingDesk?:
    | boolean
    | undefined;
  /** Parameters of the related Group Symbol */
  traderGroupSymbol: TraderGroup_Symbol[];
  /** Parameters of the related Dynamic Commissions */
  traderGroupDynamicCommission: TraderGroup_DynamicCommission[];
  /** If TRUE then traders of the Group are unable to create sub-accounts */
  copyDisabled?:
    | boolean
    | undefined;
  /** Grace period in days during which an inactivity fee is not charged for a account since last filled deal */
  inactivityGracePeriod?:
    | number
    | undefined;
  /** Period in days after which an inactivity fee is charged */
  inactivityChargePeriod?:
    | number
    | undefined;
  /** Inactivity fee amount in cents, specified in USD and converted to Deposit CCY of an account */
  inactivityFeeAmount?:
    | number
    | undefined;
  /** If TRUE then traders of the group are unable to become copy provider. Logic is on JM side */
  copyProvidingDisabled?:
    | boolean
    | undefined;
  /** If TRUE then traders are allowed to increase risk for Positions with Guaranteed Stop Loss */
  allowWorseGSL?:
    | boolean
    | undefined;
  /** Id of Swap and Dividend profile */
  swapAndDividendProfileId?:
    | Long
    | undefined;
  /** Enable/disable Negative Balance Protection */
  negativeBalanceProtection?:
    | boolean
    | undefined;
  /** If the account balance is lower than negativeBalanceProtectionLimitUsd, then negativeBalanceProtection is not applied and the operation of type BALANCE_DEPOSIT_NEGATIVE_BALANCE_PROTECTION, which sets the balance to 0, is not executed. If negativeBalanceProtection<>TRUE then negativeBalanceProtectionLimitUsd will be set to unspecified */
  negativeBalanceProtectionLimitUsd?: number | undefined;
}

/** Trader group symbol */
export interface TraderGroup_Symbol {
  /** ID of the Group Symbol */
  symbolId?:
    | Long
    | undefined;
  /** Specifies if Symbol is available for the traders of the Group */
  enabled?:
    | boolean
    | undefined;
  /**
   * Commission for the Symbol
   *
   * @deprecated
   */
  tradingCommissionRate?:
    | number
    | undefined;
  /**
   * Day of the week when SWAP charge amount will be tripled. Doesn't impact rollover commission
   *
   * @deprecated
   */
  swapRollover3Days?:
    | DayOfWeek
    | undefined;
  /**
   * SWAP value for long positions
   *
   * @deprecated
   */
  swapLong?:
    | Long
    | undefined;
  /**
   * SWAP value for short positions
   *
   * @deprecated
   */
  swapShort?:
    | Long
    | undefined;
  /**
   * Minimal order volume
   *
   * @deprecated
   */
  minVolume?:
    | Long
    | undefined;
  /**
   * Maximum order volume
   *
   * @deprecated
   */
  maxVolume?:
    | Long
    | undefined;
  /**
   * Tolerance distance
   *
   * @deprecated
   */
  tolerance?:
    | number
    | undefined;
  /**
   * Minimal order stake
   *
   * @deprecated
   */
  minStake?:
    | Long
    | undefined;
  /**
   * Maximum order stake
   *
   * @deprecated
   */
  maxStake?:
    | Long
    | undefined;
  /**
   * Date and time of charging dividends
   *
   * @deprecated
   */
  dividendTime?:
    | Long
    | undefined;
  /**
   * Charge for Guaranteed Stop Loss placement
   *
   * @deprecated
   */
  gslCharge?:
    | Long
    | undefined;
  /**
   * Minimal distance for placing Stop Loss
   *
   * @deprecated
   */
  slDistance?:
    | number
    | undefined;
  /**
   * Minimal distance for placing Take Profit
   *
   * @deprecated
   */
  tpDistance?:
    | number
    | undefined;
  /**
   * Minimal distance for placing Guaranteed Stop Loss
   *
   * @deprecated
   */
  gslDistance?:
    | number
    | undefined;
  /**
   * Commission Type
   *
   * @deprecated
   */
  commissionType?:
    | CommissionType
    | undefined;
  /**
   * Amount of minimal commission to be paid for each order
   *
   * @deprecated
   */
  minCommission?:
    | Long
    | undefined;
  /**
   * Type of minimal commission
   *
   * @deprecated
   */
  minCommissionType?:
    | MinCommissionType
    | undefined;
  /**
   * Asset of the minimal commission. Used when minCommissionType=0
   *
   * @deprecated
   */
  minCommissionAssetId?:
    | Long
    | undefined;
  /**
   * Kind of swap for swap-free accounts (USD per million USD in cents)
   *
   * @deprecated
   */
  rolloverCommission?:
    | Long
    | undefined;
  /**
   * Count of nights before first rolloverCommission charge
   *
   * @deprecated
   */
  skipRolloverDays?:
    | number
    | undefined;
  /**
   * Step for incremental change of the volume of the trade Order
   *
   * @deprecated
   */
  stepVolume?:
    | Long
    | undefined;
  /**
   * Step for incremental change of the stake of the trade Order
   *
   * @deprecated
   */
  stepStake?:
    | Long
    | undefined;
  /**
   * Total USD volume of ALL open positions allowed for the account for this symbol
   *
   * @deprecated
   */
  maxExposure?:
    | Long
    | undefined;
  /** Id of Dynamic leverage */
  leverageId?:
    | Long
    | undefined;
  /**
   * Amount of dividends Long
   *
   * @deprecated
   */
  dividendsLong?:
    | Long
    | undefined;
  /**
   * Amount of dividends Short
   *
   * @deprecated
   */
  dividendsShort?:
    | Long
    | undefined;
  /** Id of GSL Schedule */
  gslScheduleId?:
    | Long
    | undefined;
  /**
   * BookType of GroupSymbol
   *
   * @deprecated
   */
  bookType?:
    | BookType
    | undefined;
  /**
   * Payment period of rolloverCommission in days (default = 1). 1 (or 0) means daily payments, 2 each second day.
   * 3x rollover is applied only for daily payments
   *
   * @deprecated
   */
  rolloverChargePeriod?:
    | number
    | undefined;
  /**
   * Day of the week (in UTC) when Administrative Fee charge amount will be tripled. Applied only if rollover charge period = 0 or 1
   *
   * @deprecated
   */
  rolloverCommission3Days?:
    | DayOfWeek
    | undefined;
  /**
   * Specifies type of SWAP computation as PIPS (0) or PERCENTAGE (1, annual, in percent)
   *
   * @deprecated
   */
  swapCalculationType?:
    | SwapCalculationType
    | undefined;
  /**
   * Gsl execution policy
   *
   * @deprecated
   */
  gslExecutionPolicy?:
    | GSLExecutionPolicy
    | undefined;
  /** Id of commission profile */
  commissionProfileId?:
    | Long
    | undefined;
  /** Id of volume profile */
  volumeProfileId?:
    | Long
    | undefined;
  /** Id of execution profile */
  executionProfileId?:
    | Long
    | undefined;
  /** Id of protection profile */
  protectionProfileId?:
    | Long
    | undefined;
  /** Id of swapFree profile */
  swapFreeProfileId?: Long | undefined;
}

/** Trader group dynamic commission */
export interface TraderGroup_DynamicCommission {
  /** Monthly USD volume which should be reached in order to get related discount for paid commission */
  monthlyVolume?:
    | Long
    | undefined;
  /** Discount applied to the basic commission after reaching related monthlyVolume */
  discount?: number | undefined;
}

export interface GSLScheduleProfiles {
  gslSchedule: GSLScheduleProfile[];
}

export interface GSLScheduleProfile {
  /** Id of this GSL schedule */
  id: Long;
  /** Name of this GSL schedule */
  name: string;
  /** List of (time -> multiplier) schedule tiers */
  tiers: GSLScheduleTier[];
  /**
   * Specifies either schedule is deleted or not
   *
   * @deprecated
   */
  isDeleted?:
    | boolean
    | undefined;
  /**
   * Specifies either schedule is default or not
   *
   * @deprecated
   */
  isDefault?: boolean | undefined;
}

export interface GSLScheduleTier {
  /** This tier is active from startTime (Count of seconds from 00:00:00) */
  startTime: number;
  /** Tier's multiplier (in percents) */
  multiplier: number;
}

export interface OrderAction {
  /** Action id */
  id: Long;
  /** Order id */
  orderId?:
    | Long
    | undefined;
  /** Action type */
  actionType: ActionType;
  /** Action type */
  actionStatus: ActionStatus;
  /** Date and time of automatic cancellation of the pending Order */
  expirationTimestamp?:
    | Long
    | undefined;
  /** Order volume */
  volume?:
    | Long
    | undefined;
  /** Order execution price */
  price?:
    | Long
    | undefined;
  /** Price of the Stop Loss */
  stopLoss?:
    | Long
    | undefined;
  /** Price of the Take Profit */
  takeProfit?:
    | Long
    | undefined;
  /** Session Id */
  sessionId?:
    | string
    | undefined;
  /** Client request id */
  clientRequestId?:
    | string
    | undefined;
  /** Custom Order label */
  label?:
    | string
    | undefined;
  /** Custom Order comment */
  comment?:
    | string
    | undefined;
  /** Custom Order channel */
  channel?:
    | string
    | undefined;
  /** Action execution timestamp */
  executeTimestamp?:
    | Long
    | undefined;
  /** Relative Stop Loss distance */
  relativeStopLoss?:
    | Long
    | undefined;
  /** Relative Take Profit distance */
  relativeTakeProfit?:
    | Long
    | undefined;
  /** Trigger method for main pending order */
  stopTriggerMethod?:
    | OrderTriggerMethod
    | undefined;
  /** Stop trigger method for SL/TP order */
  stopLossTriggerMethod?:
    | OrderTriggerMethod
    | undefined;
  /** Date and time for execution MOO order */
  desiredOpenTimestamp?:
    | Long
    | undefined;
  /** Id of linked OCO order */
  ocoOrderId?: Long | undefined;
}

export interface EndOfDayTradersReport {
  /** Snapshot of Account's financial info */
  tradersReportData: EndOfDayTradersReport_EndOfDayTraderReportData[];
}

export interface EndOfDayTradersReport_EndOfDayTraderReportData {
  /** Date and time of Report generation */
  reportTimestamp: Long;
  /** Account's login */
  login: Long;
  /** Balance of the Account */
  balance: Long;
  /** Gross unrealized P&L on Book A */
  grossUnrealizedPnlA: Long;
  /** Net unrealized P&L on Book A */
  netUnrealizedPnlA: Long;
  /** Gross unrealized P&L on Book B */
  grossUnrealizedPnlB: Long;
  /** Net unrealized P&L on Book B */
  netUnrealizedPnlB: Long;
  /** Equity of the Account */
  equity: Long;
  /** Used margin of the Account */
  margin: Long;
  /** Free margin of the Account */
  freeMargin: Long;
  /** Shows if monetary values were multiplied by 10^8 (TRUE) or by 10^2 (FALSE). Affects balance, grossUnrealizedPnlA, netUnrealizedPnlA, grossUnrealizedPnlB, netUnrealizedPnlB, equity, margin, freeMargin */
  isPreciseMoney?:
    | boolean
    | undefined;
  /** Non-withdrawable bonus of the Account */
  nonWithdrawableBonus?: Long | undefined;
}

export interface EndOfDaySpotSnapshotReport {
  /** Snapshot of spot prices */
  endOfDaySpotSnapshotReportData: EndOfDaySpotSnapshotReport_EndOfDaySpotSnapshotReportData[];
}

export interface EndOfDaySpotSnapshotReport_EndOfDaySpotSnapshotReportData {
  /** Date and time of snapshot */
  reportTimestamp: Long;
  /** Price */
  price: Long;
  /** Price direction */
  side: TradeSide;
  /** Date and time of the price in snapshot */
  createTimestamp: Long;
  /** ID of the Symbol */
  symbolId: Long;
}

export interface EndOfDayOpenPositionsReport {
  /** Snapshot of all open Positions */
  endOfDayOpenPositionsReportData: EndOfDayOpenPositionsReport_EndOfDayOpenPositionsReportData[];
}

export interface EndOfDayOpenPositionsReport_EndOfDayOpenPositionsReportData {
  /** Date and time of snapshot */
  reportTimestamp: Long;
  /** ID of the Account */
  traderId: Long;
  /** ID of the Position */
  positionId: Long;
  /** Position opening date and time */
  openTimestamp: Long;
  /** ID of the Symbol */
  symbolId: Long;
  /** Stake of the Position */
  stake?:
    | Long
    | undefined;
  /** Volume of the Position */
  volume?:
    | Long
    | undefined;
  /** Lot Size, applicable to the Position */
  lotSize: Long;
  /** Trade side of the Position */
  tradeSide: TradeSide;
  /** Open VWAP of the Position */
  vwapPrice: Long;
  /** Margin, used by Position */
  margin: Long;
  /** Gross unrealized P&L of the Position */
  grossUnrealizedPnl: Long;
  /** Net unrealized P&L of the Position */
  netUnrealizedPnl: Long;
  /**
   * Quote to Deposit conversion rate
   *
   * @deprecated
   */
  quoteToDepositRate: Long;
  /** Last spot price used to calculate P&L */
  lastSpot: Long;
  /** Quote to Deposit conversion rate as double value (e.g. 1.23456) */
  quoteToDeposit: number;
  /** Shows if monetary values were multiplied by 10^8 (TRUE) or by 10^2 (FALSE). Affects margin, grossUnrealizedPnl, netUnrealizedPnl */
  isPreciseMoney?: boolean | undefined;
}

export interface SpotEvent {
  /** Id of the symbol */
  symbolId: Long;
  /** Represented in units equal to 1/10^5 of a price (e.g. EURJPY 128.134 = 12813400) */
  bid?:
    | Long
    | undefined;
  /** Represented in units equal to 1/10^5 of a price */
  ask?:
    | Long
    | undefined;
  /**
   * Timestamp when a spotEvent was generated, equal to the time of the last quote.
   * SpotEvent can be also generated if a quote in DOM become obsolete and dropped.
   */
  timestamp?: Long | undefined;
}

export interface Ticks {
  /** ID of the Symbol */
  symbolId: Long;
  /** Requested type of ticks */
  type: MarketDataEntryType;
  /** Historical ticks for a period */
  tickData: Ticks_TickData[];
}

export interface Ticks_TickData {
  /** Tick timestamp */
  timestamp: Long;
  /** Tick value */
  tick: Long;
}

export interface MarginCall {
  /** ID of the Trader */
  traderId: Long;
  /** Account's equity for the moment of the margin call event */
  equity: Long;
  /** Account's balance for the moment of the margin call event */
  balance?:
    | Long
    | undefined;
  /** Server's date and time when margin call was triggered */
  reachedUtcTimestamp?:
    | Long
    | undefined;
  /** Account's margin level for the moment of the margin call event */
  marginLevel?:
    | number
    | undefined;
  /** Margin level threshold that triggered this margin call event */
  marginLevelThreshold?:
    | number
    | undefined;
  /** Shows if monetary values were multiplied by 10^8 (TRUE) or by 10^2 (FALSE). Affects equity, balance */
  isPreciseMoney?: boolean | undefined;
}

export interface CommissionProfile {
  /** ID of the commission profile */
  commissionProfileId: Long;
  /** Name of the commission profile */
  name: string;
  /** Description of commission profile */
  description?:
    | string
    | undefined;
  /** Commission for the Profile */
  tradingCommissionRate: number;
  /** Commission Type */
  commissionType: CommissionType;
  /**
   * Amount of minimal commission to be paid for each order
   *
   * @deprecated
   */
  minCommission: Long;
  /** Asset of the minimal commission. Used when minCommissionType=0 */
  minCommissionType: MinCommissionType;
  /** Asset of the minimal commission. Used when minCommissionType=0 */
  minCommissionAssetId: Long;
  /** Amount of minimal commission to be paid for each order, multiplied by 10^8 */
  preciseMinCommission?:
    | number
    | undefined;
  /** This is percentage, so 1 protocol value = 0.01% */
  pnlConversionFeeRate?: number | undefined;
}

export interface VolumeProfile {
  /** ID of the volume profile */
  volumeProfileId: Long;
  /** Name of the volume profile */
  name: string;
  /** Description of volume profile */
  description?:
    | string
    | undefined;
  /** Minimal volume */
  minVolume: Long;
  /** Step for volume */
  stepVolume: Long;
  /** Maximum volume */
  maxVolume: Long;
  /** Minimal stake */
  minStake: Long;
  /** Step of stake */
  stepStake: Long;
  /** Maximum stake */
  maxStake: Long;
  /** Maximum exposure */
  maxExposure: Long;
}

export interface ExecutionProfile {
  /** ID of the execution profile */
  executionProfileId: Long;
  /** Name of the execution profile */
  name: string;
  /** Description of execution profile */
  description?:
    | string
    | undefined;
  /** Minimal book B execution delay */
  minBookBDelay: number;
  /** Maximum book B execution delay */
  maxBookBDelay: number;
  /**
   * Execution book type
   *
   * @deprecated
   */
  bookType?:
    | BookType
    | undefined;
  /** Gsl execution policy */
  gslExecutionPolicy: GSLExecutionPolicy;
  /** Determines execution policy for all opening Orders */
  executionPolicy: ExecutionPolicy;
  /** Used only if executionPolicy = BOOK_A_WITH_CONDITION */
  conditionVolumeUsd?: Long | undefined;
}

export interface ProtectionProfile {
  /** ID of the protection profile */
  protectionProfileId: Long;
  /** Name of the protection profile */
  name: string;
  /** Description of protection profile */
  description?:
    | string
    | undefined;
  /** Charge for Guaranteed Stop Loss placement */
  gslCharge: Long;
  /** Minimal distance for placing Stop Loss */
  slDistance: number;
  /** Minimal distance for placing Take Profit */
  tpDistance: number;
  /** Minimal distance for placing Guaranteed Stop Loss */
  gslDistance: number;
  /** Distance in points or percentage */
  distanceSetIn: SymbolDistanceType;
  /** Tolerance distance */
  tolerance: number;
}

export interface SwapFreeProfile {
  /** ID of the swapFree profile */
  swapFreeProfileId: Long;
  /** Name of the swapFree profile */
  name: string;
  /** Description of swapFree profile */
  description?:
    | string
    | undefined;
  /** Kind of swap for swap-free accounts (USD per million USD in cents) */
  rolloverCommission?:
    | Long
    | undefined;
  /** Count of nights before first rolloverCommission charge */
  skipRolloverDays?:
    | number
    | undefined;
  /**
   * Payment period of rolloverCommission in days (default = 1). 1 (or 0) means daily payments, 2 each second day.
   * 3x rollover is applied only for daily payments
   */
  rolloverChargePeriod?:
    | number
    | undefined;
  /** Day of the week (in UTC) when Administrative Fee charge amount will be tripled. Applied only if rollover charge period = 0 or 1 */
  rolloverCommission3Days?: DayOfWeek | undefined;
}

export interface ScheduleProfile {
  /** ID of the schedule profile */
  scheduleProfileId: Long;
  /** Name of the schedule profile */
  name: string;
  /** Description of schedule profile */
  description?:
    | string
    | undefined;
  /** Profile time zone */
  scheduleTimeZone: string;
  /** Schedule profile intervals */
  interval: Interval[];
}

/** Represents time frame of symbol session */
export interface Interval {
  /** Seconds from the beginning of Sunday 00:00:00 */
  startSecond: number;
  /** Seconds from the beginning of Sunday 00:00:00 */
  endSecond: number;
  /** If TRUE then session start is considered as a start of the Global session. Used for MOO desired timestamp validation */
  isGlobalSessionStart?:
    | boolean
    | undefined;
  /** If TRUE then session end is considered as end of the Global session. SpotEvent.sessionClose, high, low will be generated */
  isGlobalSessionEnd?: boolean | undefined;
}

export interface SwapAndDividendProfile {
  /** ID of SwapAndDividendProfile profile */
  swapAndDividendProfileId: Long;
  /** Description of SwapAndDividendProfile profile */
  name: string;
  /** Description */
  description?:
    | string
    | undefined;
  /** Modification time in the milliseconds */
  utcLastUpdateTimestamp?:
    | Long
    | undefined;
  /** List of associated symbols */
  symbol: SwapAndDividendSymbol[];
}

export interface SwapAndDividendSymbol {
  /** ID of swapAndDividendSymbol */
  symbolId: Long;
  /**
   * Day of the week when SWAP charge amount will be tripled. Doesn't impact rollover commission
   * If unspecified, default parameter from Symbol is used
   */
  swapRollover3Days?:
    | DayOfWeek
    | undefined;
  /**
   * SWAP value for long positions
   * If unspecified, default parameter from Symbol is used
   */
  swapLong?:
    | number
    | undefined;
  /**
   * SWAP value for short positions
   * If unspecified, default parameter from Symbol is used
   */
  swapShort?:
    | number
    | undefined;
  /**
   * Specifies type of SWAP computation as PIPS (0) or PERCENTAGE (1, annual, in percent)
   * If unspecified, default parameter from Symbol is used
   */
  swapCalculationType?:
    | SwapCalculationType
    | undefined;
  /**
   * Amount of dividends Long
   * If unspecified, default parameter from Symbol is used
   */
  dividendsLong?:
    | Long
    | undefined;
  /**
   * Amount of dividends Short
   * If unspecified, default parameter from Symbol is used
   */
  dividendsShort?:
    | Long
    | undefined;
  /** Date and time of charging dividends */
  dividendTime?:
    | Long
    | undefined;
  /**
   * swap is calculated every swapPeriod hours
   * If unspecified, default parameter from Symbol is used
   */
  swapPeriod?:
    | number
    | undefined;
  /**
   * from which swap period is calculated, in minutes from 00:00.
   * If unspecified, default parameter from Symbol is used
   */
  swapTime?:
    | number
    | undefined;
  /** Count of swapPeriods before the first SWAP charge */
  skipSWAPPeriods?:
    | number
    | undefined;
  /** If enabled, SWAP will be charged for all days of the week, including Saturday and Sunday */
  chargeSwapAtWeekends?: boolean | undefined;
}

export interface Holiday {
  /** ID of holiday */
  holidayId: Long;
  /** Name of the holiday */
  name: string;
  /** Description of the holiday */
  description?:
    | string
    | undefined;
  /** Timezone of the holiday */
  scheduleTimeZone: string;
  /** Holiday date. EpochMillis / 86400000 (ms * sec * min * hours) */
  holidayDate: Long;
  /** if this TRUE  then holidayDate  considered as annual event at the same date, so year is not important any more. */
  isRecurring: boolean;
  /** amount of seconds from 00:00:00 of the holiday day when holiday actually starts */
  startSecond?:
    | number
    | undefined;
  /** amount of seconds from 00:00:00 of the holiday day when holiday actually finished */
  endSecond?: number | undefined;
}

export interface HolidayProfile {
  holidayProfileId: Long;
  /** Name of the holiday profile */
  name: string;
  /** Description of the holiday profile */
  description?:
    | string
    | undefined;
  /** Ids of holiday */
  holidayId: Long[];
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}
