x-nest-service: &nest_service
  stop_grace_period: 1s
  build:
    target: 'development'
  deploy:
    resources:
      limits:
        cpus: '2'
        memory: 4Gb
      reservations:
        cpus: '1'
        memory: 2GB

x-next-service: &next_service
  stop_grace_period: 1s
  build:
    target: 'development'
  deploy:
    resources:
      limits:
        cpus: '2'
        memory: 2Gb
      reservations:
        cpus: '1'
        memory: 1GB

services:
  ## Microservices                        ##
  ##########################################
  analytics:
    profiles: [ 'dev' ]
    image: 'cubejs/cube:latest'
    working_dir: /app/apps/analytics
    platform: linux/amd64
    ports:
      - '4000:4000'
    depends_on:
      - db-migrate
      - crm-postgres
    env_file:
      - './apps/analytics/.env'
    volumes:
      - ./apps/analytics:/app/apps/analytics
    networks:
      - crm-network
  ############################
  audit:
    profiles: [ 'dev' ]
    <<: *nest_service
    working_dir: /app/apps/audit
    command: nest start --watch
    build:
      target: 'development'
      args:
        - TARGET_APP=audit
    ports:
      - '3001:3000'
      - '30001:9229'
    depends_on:
      - crm-kafka
      - crm-postgres
    env_file:
      - './apps/audit/.env'
    volumes:
      - ./apps/audit:/app/apps/audit
      - ./packages:/app/packages
    networks:
      - crm-network
  ############################
  bull-monitor:
    profiles: [ 'dev' ]
    <<: *nest_service
    working_dir: /app/apps/bull-monitor
    command: nest start --watch
    build:
      target: 'development'
      args:
        - TARGET_APP=bull-monitor
    ports:
      - '3002:3000'
    depends_on:
      - crm-redis
      - crm-gateway
    volumes:
      - ./apps/bull-monitor:/app/apps/bull-monitor
      - ./packages:/app/packages
    networks:
      - crm-network
  ############################
  compliance:
    profiles: [ 'dev' ]
    <<: *nest_service
    working_dir: /app/apps/compliance
    command: nest start --watch --debug 0.0.0.0:9229
    build:
      target: 'development'
      args:
        - TARGET_APP=compliance
    ports:
      - '3003:3000'
      - '30003:9229'
    depends_on:
      - audit
      - db-migrate
      - crm-postgres
      - crm-redis
      - crm-kafka
      - crm-gateway
    volumes:
      - ./apps/compliance:/app/apps/compliance
      - ./packages:/app/packages
    networks:
      - crm-network
  ############################
  crm:
    profiles: [ 'dev' ]
    <<: *nest_service
    working_dir: /app/apps/crm
    command: nest start --watch --debug 0.0.0.0:9229
    build:
      target: 'development'
      args:
        - TARGET_APP=crm
    ports:
      - '3004:3000'
      - '30004:9229'
    depends_on:
      - audit
      - db-migrate
      - crm-postgres
      - crm-redis
      - crm-kafka
      - crm-gateway
    volumes:
      - ./apps/crm:/app/apps/crm
      - ./packages:/app/packages
    networks:
      - crm-network
  ############################
  frontend:
    profiles: [ 'dev' ]
    <<: *next_service
    working_dir: /app/apps/frontend
    command: pnpm dev
    build:
      target: 'development'
      args:
        - TARGET_APP=frontend
    ports:
      - '3000:3000'
    volumes:
      - ./apps/frontend:/app/apps/frontend
    networks:
      - crm-network
  ############################
  notification:
    profiles: [ 'dev' ]
    <<: *nest_service
    working_dir: /app/apps/notification
    command: nest start --watch --debug 0.0.0.0:9229
    build:
      target: 'development'
      args:
        - TARGET_APP=notification
    ports:
      - '3005:3000'
      - '30005:9229'
    depends_on:
      - audit
      - bull-monitor
      - db-migrate
      - maildev
      - crm-postgres
      - crm-redis
      - crm-kafka
      - crm-gateway
    volumes:
      - ./apps/notification:/app/apps/notification
      - ./packages:/app/packages
    networks:
      - crm-network
  ############################
  payment:
    profiles: [ 'dev' ]
    <<: *nest_service
    working_dir: /app/apps/payment
    command: nest start --watch --debug 0.0.0.0:9229
    build:
      target: 'development'
      args:
        - TARGET_APP=payment
    ports:
      - '3006:3000'
      - '30006:9229'
    depends_on:
      - audit
      - db-migrate
      - crm-postgres
      - crm-redis
      - crm-kafka
      - crm-gateway
    volumes:
      - ./apps/payment:/app/apps/payment
      - ./packages:/app/packages
    networks:
      - crm-network
  ############################
  prop:
    profiles: [ 'dev' ]
    <<: *nest_service
    working_dir: /app/apps/prop
    command: nest start --watch --debug 0.0.0.0:9229
    build:
      target: 'development'
      args:
        - TARGET_APP=prop
    ports:
      - '3007:3000'
      - '30007:9229'
    depends_on:
      - audit
      - db-migrate
      - crm-postgres
      - crm-redis
      - crm-kafka
      - crm-gateway
    volumes:
      - ./apps/prop:/app/apps/prop
      - ./packages:/app/packages
    networks:
      - crm-network
  ############################
  user:
    profiles: [ 'dev' ]
    <<: *nest_service
    working_dir: /app/apps/user
    command: nest start --watch --debug 0.0.0.0:9229
    build:
      target: 'development'
      args:
        - TARGET_APP=user
    ports:
      - '3008:3000'
      - '30008:9229'
    depends_on:
      - audit
      - bull-monitor
      - db-migrate
      - crm-postgres
      - crm-redis
      - crm-kafka
      - crm-gateway
    volumes:
      - ./apps/user:/app/apps/user
      - ./packages:/app/packages
    networks:
      - crm-network

  ## Infrastructure Containers            ##
  ##########################################
  crm-postgres:
    profiles: [ 'dev', 'tools' ]
    image: postgres:17.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - crm-postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: crm_db
    networks:
      - crm-network
  ############################
  crm-redis:
    profiles: [ 'dev' ]
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - crm-network
  ############################
  crm-kafka:
    profiles: [ 'dev' ]
    image: bitnamilegacy/kafka:3.5.1
    healthcheck:
      test: [ 'CMD-SHELL', 'exit 0' ]
      interval: 1s
      timeout: 5s
      retries: 500
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=crm-zookeeper:2181
    ports:
      - '9092:9092'
      - '9093:9093'
    depends_on:
      - crm-zookeeper
      - crm-ui-kafka
    networks:
      - crm-network
  ############################
  crm-gateway:
    profiles: ['dev']
    image: devopsfaith/krakend:2.9.2-watch
    stop_grace_period: 1s
    volumes:
      - ./apps/gateway:/etc/krakend
    ports:
      - '8080:8080'
      - '9090:9090'
    environment:
      - FC_ENABLE=1
      - FC_SETTINGS=/etc/krakend/config/services
      - FC_PARTIALS=/etc/krakend/config/partials
      - FC_OUT=krakend.json
      - PORT=8080
    command: ['run', '-dc', '/etc/krakend/krakend.tmpl']
    networks:
      - crm-network
  ############################
  crm-zookeeper:
    profiles: [ 'dev' ]
    image: bitnamilegacy/zookeeper:3.9.0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - crm-network
  ############################
  crm-ui-kafka:
    profiles: [ 'dev' ]
    image: provectuslabs/kafka-ui:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=crm-kafka:9092
    ports:
      - '9080:8080'
    networks:
      - crm-network
  ############################
  maildev:
    profiles: [ 'dev' ]
    image: maildev/maildev:latest
    ports:
      - '1025:1025'
      - '1080:1080'
    networks:
      - crm-network
  ############################

  ## Utils Containers                     ##
  ##########################################
  utils:
    profiles: ['tools']
    build:
      target: 'base'
    command: 'echo ''Specify your command like "pnpm db:migrate:up" in the docker-compose command'''
    env_file:
      - apps/crm/.env
    volumes:
      - ./:/app
    depends_on:
      - crm-postgres
    networks:
      - crm-network
  db-migrate:
    profiles: [ 'dev' ]
    build:
      target: 'base'
    command: pnpm --filter @crm/database db:migrate:up
    env_file:
      - apps/crm/.env
    volumes:
      - ./:/app
    depends_on:
      - crm-postgres
    networks:
      - crm-network

volumes:
  crm-postgres-db:

networks:
  crm-network:
    driver: bridge
