// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.1
// source: CommonModelMessages_External.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

/** Enum for payload type */
export enum ProtoPayloadType {
  PROTO_MESSAGE = 5,
  PROTO_SERVER_DEPTH_QUOTES_EVENT = 2,
  PROTO_SERVER_SPOT_EVENT = 3,
  PROTO_SERVER_DEPTH_EVENT = 4,
  PROTO_SERVER_TRAILING_SL_CHANGED_EVENT = 6,
  PROTO_SERVER_MARKET_DATA_EVENT = 7,
  ERROR_RES = 50,
  HEARTBEAT_EVENT = 51,
  PING_REQ = 52,
  PING_RES = 53,
  REGISTER_CSERVER_CONNECTION_REQ = 54,
  REGISTER_CSERVER_CONNECTION_RES = 55,
  UNREGISTER_CSERVER_CONNECTION_REQ = 56,
  UNREGISTER_CSERVER_CONNECTION_RES = 57,
  REGISTER_CID_CONNECTION_REQ = 58,
  REGISTER_CID_CONNECTION_RES = 59,
  UNREGISTER_CID_CONNECTION_REQ = 60,
  UNREGISTER_CID_CONNECTION_RES = 61,
  AVAILABLE_SERVICES_EVENT = 66,
  PROTO_UPV1_EVENT_SUBSCRIBE_REQ = 67,
  PROTO_UPV1_EVENT_SUBSCRIBE_RES = 68,
  UNRECOGNIZED = -1,
}

/** Enum for error code */
export enum ProtoErrorCode {
  UNKNOWN_ERROR = 1,
  UNSUPPORTED_MESSAGE = 2,
  INVALID_REQUEST = 3,
  WRONG_PASSWORD = 4,
  TIMEOUT_ERROR = 5,
  ENTITY_NOT_FOUND = 6,
  CANT_ROUTE_REQUEST = 7,
  FRAME_TOO_LONG = 8,
  MARKET_CLOSED = 9,
  CONCURRENT_MODIFICATION = 10,
  BLOCKED_PAYLOAD_TYPE = 11,
  DATASTORE_IS_NOT_AVAILABLE = 12,
  UNRECOGNIZED = -1,
}

/** Type for range */
export interface ProtoIntRange {
  /** Start of the range */
  from?:
    | number
    | undefined;
  /** End of the range */
  to?: number | undefined;
}

/** Type for range (long) */
export interface ProtoLongRange {
  /** Start of the range */
  from?:
    | Long
    | undefined;
  /** End of the range */
  to?: Long | undefined;
}

/** Type for double range */
export interface ProtoDoubleRange {
  /** Start of the range */
  from?:
    | number
    | undefined;
  /** End of the range */
  to?: number | undefined;
}

/** Type for geo info */
export interface ProtoGeoInfo {
  /** Country ISO code */
  countryIsoCode?:
    | string
    | undefined;
  /** City name */
  cityName?: string | undefined;
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}
