// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.1
// source: CommonMessages_External.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { ProtoPayloadType } from "./CommonModelMessages_External";

/** Message type */
export interface ProtoMessage {
  /** Type of payload */
  payloadType: number;
  /** Payload */
  payload?:
    | Buffer
    | undefined;
  /** Client message id, use this for matching the response with the initial request */
  clientMsgId?: string | undefined;
}

/** Error response message */
export interface ProtoErrorRes {
  /** Type of payload */
  payloadType?:
    | ProtoPayloadType
    | undefined;
  /** Error code */
  errorCode: string;
  /** Error description */
  description?:
    | string
    | undefined;
  /** UNIX timestamp in milliseconds. If server is under maintenance, this field indicates the estimated time when the server will be operational again */
  maintenanceEndTimestamp?: Long | undefined;
}

/** Heartbeat used for keeping connection alive */
export interface ProtoHeartbeatEvent {
  /** Type of payload */
  payloadType?: ProtoPayloadType | undefined;
}

/** Message used for sending a ping request to the server */
export interface ProtoPingReq {
  payloadType?:
    | ProtoPayloadType
    | undefined;
  /** UNIX timestamp in milliseconds, you will receive a response with the same timestamp */
  timestamp: Long;
}

/** Response to a ProtoPingReq message */
export interface ProtoPingRes {
  payloadType?:
    | ProtoPayloadType
    | undefined;
  /** UNIX timestamp in milliseconds, this is the timestamp of the request */
  timestamp: Long;
}

/** CS-13238. Event that contains backend servises status. Proxy sends it to client when he connects and to all clients sessions when services availability changes. If connection to service not configured - relevant service field doesn't sent. */
export interface ProtoAvailableServicesEvent {
  payloadType?: ProtoPayloadType | undefined;
  socialAvailable?: boolean | undefined;
  copyAvailable?: boolean | undefined;
  datastoreAvailable?: boolean | undefined;
  blotterAvailable?: boolean | undefined;
}

export interface ProtoUPv1EventSubscribeReq {
  payloadType?:
    | ProtoPayloadType
    | undefined;
  /** List of event payload types which client intends to receive */
  subscriptionPayloadType: number[];
}

export interface ProtoUPv1EventSubscribeRes {
  payloadType?: ProtoPayloadType | undefined;
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}
