export enum AuditTarget {
  USER = 'user',
  DOCUMENT = 'document',
  NOTE = 'note',
  WALLET = 'wallet',
  TRADING_ACCOUNT = 'trading_account',
  TRADING_ACCOUNT_SCHEMA = 'trading_account_schema',
  SESSION = 'session',
  SETTING = 'setting',
  INTEGRATION = 'integration',
  SERVER = 'server',
  PLATFORM_CLIENT = 'platform_client',
  TAG = 'tag',
  OTHER = 'other',
}
