export enum OrderType {
  BUY_LIMIT = 'BUY_LIMIT',
  SELL_LIMIT = 'SELL_LIMIT',
  BUY_STOP = 'BUY_STOP',
  SELL_STOP = 'SELL_STOP',
  BUY_STOP_LIMIT = 'BUY_STOP_LIMIT',
  SELL_STOP_LIMIT = 'SELL_STOP_LIMIT',
}
